### ISSUE TITLE
The link for downloading Cholec80-CSV data is not working.

### ISSUE THREAD

**Issue by lucaszbk** [ManuelRios18/CHOLEC80-CVS-PUBLIC#1]
May we get new link please? Thank you so much

**Comment by ManuelRios18** [comment]
@lucaszbk  Sorry for the late response, 

The link points to: https://springernature.figshare.com/articles/dataset/Cholec80-CVS_An_open_dataset_with_an_evaluation_of_Strasberg_s_critical_view_of_safety_for_Artificial_Intelligence/22183885?backTo=/collections/Cholec80-CVS_An_open_dataset_with_an_evaluation_of_Strasberg_s_critical_view_of_safety_for_AI/5880458


It works for me, is not working for you?
